export default {
    pwdIsEmpty: '密码不能为空',
    pwdInconformity: '两次密码不一致',
    createPwd: '密码长度至少9位，不包含空格',
    serviceException: '服务器异常,请联系管理员',
    emptyResult: '无查询结果',
    emptyAddress: '请输入对方账户地址',
    errorGasLimit: 'Gas Limit不正确',
    errorValue: '转账数额不正确',
    transactionFail: '转账失败',
    transactionSucc: '转账成功',
    enterPwd: '请输入密码',
    importSucc:'导入成功',
    unlockSucc: '解锁成功',
    unlockFailByPwd: '解锁失败，密码错误',
    invalidGas: '无效gas上限。(Must be integer. Try 21000-4000000.)',
    invalidPrivateKey: '无效的私钥',
    invalidMnemonic: '无效的助记词',
    invalidAddress: '无效的账户地址',
    selectAnFile: '请选择keystore文件',
    corretWalletFile: '已选择钱包文件，请输入密码',
    invalidWalletFile: '不支持的钱包文件',
    invalidFile: '错误的文件类型',
    readFileErr: '读取文件失败',
    diffrentAccount:'输入账户与当前登录账户不一致，是否把当前登录账户替换',
    mustSelectAnApp:'请选择需要创建的应用',
    balanceNotEnough:'余额不足'
}
